// toolbar.js - global
(function(){
  let toolbar; let statsEl;
  function createToolbar(){ if(toolbar) return toolbar; const settings=window.ExcelHelperNS.getSettings(); toolbar=document.createElement('div'); toolbar.id='excel-helper-toolbar'; toolbar.style.cssText='position:fixed;top:10px;left:10px;z-index:10000;background:#fff;border:1px solid #ccc;padding:10px;border-radius:6px;font:12px system-ui;min-width:220px;box-shadow:0 4px 12px rgba(0,0,0,.15);cursor:move;';
    const hintText='Sürükle: Alan | Ctrl: Çoklu | Shift: Satır | Alt: Sütun';
    toolbar.innerHTML=`<div style="font-weight:600;margin-bottom:6px;">Excel Helper</div>
<button id="eh-toggle" title="${hintText}" style="width:100%;padding:6px;border:none;border-radius:4px;background:${settings.selectionMode?'#28a745':'#0078D4'};color:#fff;cursor:pointer;">Seçim: ${settings.selectionMode?'AÇIK':'KAPALI'}</button>
<div id="eh-mode-hint" style="margin-top:4px;font-size:10px;color:#444;line-height:1.2;">${hintText}</div>
<div style="display:flex;gap:4px;margin-top:6px;"><button id="eh-fastcopy" title="Seçimi kopyala" style="flex:1;padding:6px;border:none;border-radius:4px;background:#17a2b8;color:#fff;cursor:pointer;">Kopyala</button><button id="eh-export" style="flex:1;padding:6px;border:none;border-radius:4px;background:#6f42c1;color:#fff;cursor:pointer;">Excel</button></div>
<div style="display:flex;gap:4px;margin-top:6px;"><button id="eh-exportcsv" title="Seçimi CSV kaydet" style="flex:1;padding:6px;border:none;border-radius:4px;background:#455a64;color:#fff;cursor:pointer;">CSV</button><button id="eh-filters" style="flex:1;padding:6px;border:none;border-radius:4px;background:#ff9800;color:#fff;cursor:pointer;">Filtre</button><button id="eh-clearfilters" title="Tüm filtreleri temizle" style="flex:1;padding:6px;border:none;border-radius:4px;background:#9e9e9e;color:#fff;cursor:pointer;">Temizle</button></div>
<div id="eh-stats" style="margin-top:6px;padding:4px 6px;background:#f7f7f7;border:1px solid #e2e2e2;border-radius:4px;font-size:10px;color:#333;display:flex;flex-direction:column;gap:2px;"></div>
<div style="margin-top:6px;font-size:10px;color:#666;text-align:center;">Sürükle</div>`;
    statsEl=toolbar.querySelector('#eh-stats');
    toolbar.style.left=settings.toolbarPosition.x+'px'; toolbar.style.top=settings.toolbarPosition.y+'px'; document.body.appendChild(toolbar); let down=false,sx=0,sy=0,ox=0,oy=0; toolbar.addEventListener('mousedown',e=>{ if(e.target.tagName==='BUTTON' || e.target.closest('#eh-stats')) return; down=true; sx=e.clientX; sy=e.clientY; const r=toolbar.getBoundingClientRect(); ox=r.left; oy=r.top; }); document.addEventListener('mousemove',e=>{ if(!down) return; const nx=ox+(e.clientX-sx); const ny=oy+(e.clientY-sy); toolbar.style.left=nx+'px'; toolbar.style.top=ny+'px'; }); document.addEventListener('mouseup',()=>{ if(down){ down=false; const r=toolbar.getBoundingClientRect(); window.ExcelHelperNS.updateToolbarPosition(r.left,r.top);} }); toolbar.querySelector('#eh-toggle').addEventListener('click',()=>{ const newMode=window.ExcelHelperNS.toggleSelectionMode(); const btn=toolbar.querySelector('#eh-toggle'); btn.textContent='Seçim: '+(newMode?'AÇIK':'KAPALI'); btn.style.background=newMode?'#28a745':'#0078D4'; if(!newMode){ window.ExcelHelperNS.clearSelection(); window.ExcelHelperNS.updateStatusPanel && window.ExcelHelperNS.updateStatusPanel(); updateToolbarStats(); } }); toolbar.querySelector('#eh-export').addEventListener('click',()=>window.ExcelHelperNS.exportSelectionToExcel()); toolbar.querySelector('#eh-exportcsv').addEventListener('click',()=>window.ExcelHelperNS.exportSelectionToCSV && window.ExcelHelperNS.exportSelectionToCSV()); toolbar.querySelector('#eh-filters').addEventListener('click',()=>window.ExcelHelperNS.toggleFilters()); toolbar.querySelector('#eh-clearfilters').addEventListener('click',()=>{ window.ExcelHelperNS.clearAllFilters && window.ExcelHelperNS.clearAllFilters(); updateToolbarStats(); }); toolbar.querySelector('#eh-fastcopy').addEventListener('click',()=>{ const aoa=window.ExcelHelperNS.getSelectionAOA(); if(!aoa.length){ alert('Seçim yok'); return; } const txt=aoa.map(r=>r.join('\t')).join('\n'); navigator.clipboard.writeText(txt).then(()=>{ console.log('[ExcelHelper] Kopyalandı'); }).catch(()=>alert('Kopyalama başarısız')); }); updateToolbarStats(); return toolbar; }
  function updateToolbarStats(){ if(!statsEl) return; const selCount=(window.ExcelHelperNS.getSelectedCells? window.ExcelHelperNS.getSelectedCells().length:0); const settings=window.ExcelHelperNS.getSettings? window.ExcelHelperNS.getSettings():{}; const filterCols=settings.lastFilterActiveCount||0; statsEl.innerHTML=`<div>Seçili Hücre: <b>${selCount}</b></div><div>Aktif Filtre Kolon: <b>${filterCols}</b></div>`; }
  function initToolbar(){ createToolbar(); const bar=document.getElementById('excel-helper-toolbar'); if(!bar) return; const settings=window.ExcelHelperNS.getSettings(); if(!settings.toolbarVisible) bar.style.display='none'; document.addEventListener('keydown',e=>{ if(e.ctrlKey && e.shiftKey && e.key.toLowerCase()==='e'){ const ns=window.ExcelHelperNS.toggleToolbarVisible(); bar.style.display=ns?'block':'none'; } }); }
  window.ExcelHelperNS = window.ExcelHelperNS || {}; Object.assign(window.ExcelHelperNS,{initToolbar, updateToolbarStats});
})();
